export const CODEINPUT_INPUT_CODE = 'CODEINPUT_INPUT_CODE';
export const CODEBLOCK_REQUEST = 'CODEBLOCK_REQUEST';
export const CODEBLOCK_SUCCEED = 'CODEBLOCK_SUCCEED';
export const CODEBLOCK_FAIL = 'CODEBLOCK_FAIL';
export const CODEBLOCK_WRITE_TO_BOX = 'CODEBLOCK_WRITE_TO_BOX';
