export const CODEINPUT_INPUT_CODE = 'CODEINPUT_INPUT_CODE';
export const CODEBLOCK_REQUEST = 'CODEBLOCK_FETCH_CODE';
export const CODEBLOCK_SUCCEED = 'CODEBLOCK_RECEIVE_CODE';
export const CODEBLOCK_FAIL = 'CODEBLOCK_IMPORT_CODE';
